### ISSUE TITLE
add --only-explicit flag

### ISSUE THREAD

**Issue by luizkowalski** [mattbrictson/bundle_update_interactive#55]
the `bundle outdated` command has a flag called `--only-explicit` that only lists gems that are declared in the Gemfile, excluding dependencies. It would be nice to have the same option here. In my case, there are A LOT of dependencies listed, and it is a bit hard to make sense of what's a gem that I have installed and what's just a dependency of something else

**Comment by mattbrictson** [comment]
Thanks for the suggestion! I was not aware of `--only-explicit`. I agree that this could be a useful feature.

I don't have the bandwidth to work on this at the moment, but I will accept a PR.
